CREATE TABLE EMPLOYEE (
 EmpNo INTEGER NOT NULL,
 EmpFirstName VARCHAR(20) NOT NULL,
 EmpLastName VARCHAR(20) NOT NULL,
 DeptNo CHAR(2) NULL);
INSERT INTO EMPLOYEE VALUES (25348, 'Matthew', 'Smith' ,'d3')
INSERT INTO EMPLOYEE VALUES (10102, 'Ann' , 'Jones' ,'d3')
INSERT INTO EMPLOYEE VALUES (18316, 'John' , 'Barrimore','d1')
INSERT INTO EMPLOYEE VALUES (29346, 'James' , 'James' ,'d2')
INSERT INTO EMPLOYEE VALUES ( 9031, 'Elsa' , 'Bertoni' ,'d2')
INSERT INTO EMPLOYEE VALUES ( 2581, 'Elke' , 'Hansel' ,'d2')
INSERT INTO EMPLOYEE VALUES (28559, 'Sybill' , 'Moser' ,'d1')