DROP TABLE D_Sales_Rep
DROP TABLE D_Customer
DROP TABLE D_Order
DROP TABLE D_Product

CREATE TABLE D_Product (
ProductID			INT NOT NULL PRIMARY KEY,
No_of_Units			INT  NOT NULL,
Description			VARCHAR(20) NOT NULL,
Min_Level			INT NOT NULL,
Cat					VARCHAR(20) NOT NULL,
Unit_Price			MONEY NOT NULL,
Discount			INT NOT NULL
)

CREATE TABLE D_Order (
OrderID				INT NOT NULL PRIMARY KEY,
ProductID			INT NOT NULL REFERENCES D_Product(ProductID),
No_of_Units			INT NOT NULL,
Order_Status		VARCHAR(20) NOT NULL,
Quoated_Price		MONEY NOT NULL
)

CREATE TABLE D_Customer (
CustID				INT PRIMARY KEY,
OrderID				INT REFERENCES D_Order(OrderID),
Lname				VARCHAR(20) NOT NULL,
Fname				VARCHAR(20) NOT NULL,
Order_Date			DATE NOT NULL,

)

CREATE TABLE D_Sales_Rep (
SalesrepID			INT NOT NULL PRIMARY KEY,
CustID				INT NOT NULL REFERENCES D_Customer(CustID),
Lname				VARCHAR(20) NOT NULL,
Fname				VARCHAR(20) NOT NULL,
)